const path = require("path");
const configureSvgIcon = require("react-svg-icon-generator").default;

configureSvgIcon({
  comment         : "Generated by gulp svg-icon, if you add new icon run gulp svg-icon",
  componentName   : "Icon",
  destination     : path.join(__dirname, "src", "components", "Icon.js"),
  keepFillColor   : false,
  native          : false,
  radium          : true,
  reactPureRender : true,
  svgDir          : path.join(__dirname, "icons"),
  template        : path.join(__dirname, "template", "icon.nunjucks"),
});
