type ChatOutput implements Base {
  messages: String! @id
  passenger: ID! @id
  driver: ID! @id
  ride: ID! @id
}

type Chat implements Base @entity {
  messages: [Message!]! @link
  passenger: User @link
  driver: User @link
  ride: Ride! @link
}


extend type Query {
  CHAT_GET(chatId: String!): ChatOutput
}
extend type Mutation {
  CHAT_SEND_MESSAGE(chatId: String!, text: String!): MessageOutput!
}

extend type Subscription {
  ON_MESSAGE: MessageOutput!
}
