type PlaceOutput {
  _id: ID
  createdAt: String!
  updatedAt: String
  name: String!
  lat: Float!
  lng: Float!
  address: String!
  isFav: Boolean!
  user: ID!
}
type Place @entity {
  _id: ID! @id
  createdAt: String! @column(overrideType: "Date")
  updatedAt: String @column(overrideType: "Date")
  name: String! @column
  lat: Float! @column
  lng: Float! @column
  address: String! @column
  isFav: Boolean! @column
  user: User! @link
}

