type Place implements Base @entity {
  name: String! @column
  lat: Float! @column
  lng: Float! @column
  address: String! @column
  isFav: Boolean! @column
  user: User! @link
}

type PlaceOutput implements Base {
  name: String!
  lat: Float!
  lng: Float!
  address: String!
  isFav: Boolean!
  user: ID!
}
