scalar Date

interface Base @abstractEntity(discriminatorField: "_?") {
  _id: ID! @id
  createdAt: String! @column(overrideType: "Date")
  updatedAt: String @column(overrideType: "Date")
}

type Query {
  _: String
}

type Mutation {
  _: String
}

type Subscription {
  _: String
}
