enum Plan {
  TEAM
  INDIVIDUAL
  SUPER
}


type Team @entity {
  _id: String! @id
  plan: Plan! @column
  name: String! @column
  createdAt: String! @column(overrideType: "Date")
  updatedAt: String! @column(overrideType: "Date")
  users: [User!]! @link
}

input inputCreateTeam {
  name: String!
  email: String!
  password: String!
  plan: Plan
}
extend type Mutation {
  # Output is success message
  TEAM_CREATE(token: String!): String!
  TEAM_BEFORE_CREATE(input: inputCreateTeam): String!
}
