enum Plan {
  TEAM
  INDIVIDUAL
  SUPER
}


type Team @entity {
  _id: String! @id
  plan: Plan! @column
  name: String! @column
  createdAt: String! @column(overrideType: "Date")
  updatedAt: String! @column(overrideType: "Date")
  users: [User!]! @link
}
