type LastPosition {
  lat: Float
  lng: Float
  orientation: Float
}

type User @entity(embedded: true) {
  _id: String! @id
  fbid: String @column
  email: String @column
  verifiedEmail: Boolean! @column
  name: String! @column
  age: Int @column
  password: String @column
  phoneNumber: String @column
  verifiedPhoneNumber: Boolean! @column
  profilePhoto: String @column
  isDriving: Boolean! @column
  isRiding: Boolean! @column
  isTaken: Boolean! @column
  lastPosition: LastPosition @column
  createdAt: String! @column(overrideType: "Date")
  updatedAt: String! @column(overrideType: "Date")
  chat: Chat @link
  places: [Place!]! @link
  messages: [Message!]! @link
  # verifications: [Verification] @link
  ridesAsPassenger: [Ride!]! @link
  ridesAsDriver: [Ride!]! @link
}

extend type Mutation {
  USER_FB_CONNECT(name: String!, email: String, fbid: String!): String!
  # output is token
  USER_EMAIL_SIGN_IN(email: String!, password: String!): String!
  # output is token
  USER_EMAIL_SIGN_UP(name: String!,email: String!,password: String!,profilePhoto: String!,age: Int!,phoneNumber: String!): String!
  USER_UPDATE_PROFILE(name: String,email: String,profilePhoto: String): User!
  USER_TOGGLE_DRIVING_MODE: Boolean!
  USER_REPORT_MOVEMENT(lat: Float, lng: Float, orientation: Float): LastPosition!
  USER_ADD_PLACE(name: String!, lat: Float!, lng: Float!, address: String!, isFav: Boolean!): Boolean!
  USER_EDIT_PLACE(placeId: String!, name: String, isFav: Boolean): Boolean!
  USER_REMOVE_PLACE(placeId: String!): Boolean!
  USER_GET_NEARBY_DRIVERS: [User]!
}

extend type Query {
  USER_GET: User
  USER_GET_PLACES: [Place]!
}

extend type Subscription {
  USER_DRIVERS_GET: [User]!
}
