type LastPosition {
  lat: Float
  lng: Float
  orientation: Float
}

type User @entity {
  _id: ID! @id
  createdAt: String! @column(overrideType: "Date")
  updatedAt: String @column(overrideType: "Date")
  fbid: String @column
  email: String @column
  verifiedEmail: Boolean! @column
  name: String! @column
  age: Int @column
  password: String @column
  phoneNumber: String @column
  verifiedPhoneNumber: Boolean! @column
  profilePhoto: String @column
  isDriving: Boolean! @column
  isRiding: Boolean! @column
  isTaken: Boolean! @column
  lastPosition: LastPosition @column
  places: [Place!]! @link
  messages: [Message!]! @link
  ridesAsPassenger: [Ride!]! @link
  ridesAsDriver: [Ride!]! @link
  chatsAsPassenger: [Chat!]! @link
  chatsAsDriver: [Chat!]! @link
}

type UserOutput {
  _id: ID
  createdAt: String!
  updatedAt: String
  fbid: String
  email: String
  verifiedEmail: Boolean!
  name: String!
  age: Int
  password: String
  phoneNumber: String
  verifiedPhoneNumber: Boolean!
  profilePhoto: String
  isDriving: Boolean!
  isRiding: Boolean!
  isTaken: Boolean!
  lastPosition: LastPosition
  places: [ID!]!
  messages: [ID!]!
  ridesAsPassenger: [ID!]!
  ridesAsDriver: [ID!]!
  chatsAsPassenger: [ID!]!
  chatsAsDriver: [ID!]!
}

extend type Mutation {
  USER_FB_CONNECT(name: String!, email: String, fbid: String!): String!
  USER_EMAIL_SIGN_IN(email: String!, password: String!): String!
  USER_EMAIL_SIGN_UP(name: String!,email: String!,password: String!,profilePhoto: String!,age: Int!,phoneNumber: String!): String!
  USER_UPDATE_PROFILE(name: String,email: String,profilePhoto: String): UserOutput!
  USER_TOGGLE_DRIVING_MODE: Boolean!
  USER_REPORT_MOVEMENT(lat: Float, lng: Float, orientation: Float): LastPosition!
  USER_ADD_PLACE(name: String!, lat: Float!, lng: Float!, address: String!, isFav: Boolean!): Boolean!
  USER_EDIT_PLACE(placeId: String!, name: String, isFav: Boolean): Boolean!
  USER_REMOVE_PLACE(placeId: String!): Boolean!
  USER_GET_NEARBY_DRIVERS: [UserOutput]!
}

extend type Query {
  USER_GET: UserOutput
  USER_GET_PLACES: [PlaceOutput]!
}

extend type Subscription {
  USER_DRIVERS_GET: UserOutput!
}
