# verify email | phone by sending verification key to him

enum VerificationTarget {
  PHONE
  EMAIL
}

type Verification @entity {
  _id: String! @id
  target: VerificationTarget! @column
  payload: String! @column
  key: String! @column
  createdAt: String! @column(overrideType: "Date")
  updatedAt: String! @column(overrideType: "Date")
  # user: User! @embedded
}
