export type ErrorType = "UnknownError"
  | "ForbiddenError"
  | "AuthenticationRequiredError"
  | "AlreadyExistsError"
  | "InvalidInputError"
  | "ValidationError"
  | "NotFoundInDBError"
  | "InvalidTokenError"
  | "PhoneNotVerifiedError"
  | "AuthenticationFailedError";
